### PR TITLE
Di 22352 create account users schema changes

### PR DESCRIPTION
**Pull request by saargt**

### CODE REVIEW

**Comment by ShirMarciano** [comment]
@saargt can you explain me what is all the code deletion?

**Review by ShirMarciano — COMMENTED** [review]
@saargt can you please explain me what is all the code deletion?

**Comment by saargt** [comment]
> @saargt can you please explain me what is all the code deletion?

@ShirMarciano Sure.
Since Core now handles the translation between ADAL and PAPI references (and vise versa) I deleted the following:
1. In [server-side/api.ts] I deleted the DIMX relations endpoints for both import and export.
2. In installation - simplification of the upgrade function. Used to have a ton of Ifs.
3. In [shared/src/accountUsersCore.service.ts] There's no longer need to handle the translation of references. The only thing left in that class is adding the filtering with Hidden=0.
4. In [shared/src/iCoreService.ts] There's no longer any need for Dimx import and export handling. So these functions are also deleted from [shared/src/core.service.ts]

**Comment by ShirMarciano** [comment]
> > @saargt can you please explain me what is all the code deletion?
> 
> @ShirMarciano Sure. Since Core now handles the translation between ADAL and PAPI references (and vise versa) I deleted the following:
> 
> 1. In [server-side/api.ts] I deleted the DIMX relations endpoints for both import and export.
> 2. In installation - simplification of the upgrade function. Used to have a ton of Ifs.
> 3. In [shared/src/accountUsersCore.service.ts] There's no longer need to handle the translation of references. The only thing left in that class is adding the filtering with Hidden=0.
> 4. In [shared/src/iCoreService.ts] There's no longer any need for Dimx import and export handling. So these functions are also deleted from [shared/src/core.service.ts]

Thanks

**Pull request merged**
